name: anandhu_s_application4
description: A new Flutter project.
version: 1.0.0+17

publish_to: 'none'

environment: 
  sdk: ">=3.4.4 <4.0.0"
dependencies: 
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.9
  get: ^4.6.6
  percent_indicator: ^4.2.3
  shared_preferences: ^2.2.2
  connectivity_plus: ^6.1.0
  flutter_rating_bar: ^4.0.1
  outline_gradient_button: ^2.0.1+1
  flutter_svg_provider: ^1.0.4
  google_fonts: 
  country_code_picker: 
  country_picker: 
  pinput: 
  intl:
  aws_s3_upload_lite: ^0.1.3
  aws_sdk:
  google_sign_in: ^6.2.1
  flutter_gemini: ^2.0.4
  flutter_local_notifications: any
  carousel_slider: ^5.0.0
  



 
  dio: 
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.1
  firebase_storage: ^12.3.7
  firebase_messaging: ^15.1.6

 
  multi_dropdown:
  socket_io_client: ^2.0.3+1

  syncfusion_flutter_pdfviewer: ^28.2.7
#  assets_audio_player: ^3.1.1
  audio_video_progress_bar: ^2.0.3
#  video_player: 2.9.2
  just_audio: ^0.9.20
  shimmer: ^3.0.0
  flutter_spinkit: ^5.2.1
  chewie: ^1.7.5
  image_picker: ^1.0.8
  zego_uikit_prebuilt_call: ^4.16.20
  zego_express_engine: ^3.17.1
  permission_handler: ^11.3.1
  path_provider: ^2.1.4
  http:
  file_picker: ^8.0.6
  flutter_timer_countdown: ^1.0.7
  flick_video_player: ^0.9.0
  razorpay_flutter: ^1.3.7
  photo_view: ^0.15.0
  open_file: ^3.3.2
#  awesome_notifications: ^0.9.3+1
  record: 
    git:
      url: https://github.com/llfbandit/record.git
      ref: 5.1.2
      path: record

  audioplayers: ^6.1.0
#  zego_uikit_beauty_plugin: ^1.7.3
  crypto: ^3.0.5
  flutter_image_compress: ^2.3.0
  lottie: ^3.0.0
  flutter_animate: ^4.5.0
 # zego_uikit_beauty_plugin: ^1.7.3
  #zego_effects_plugin: ^1.0.18
  firebase_crashlytics: ^4.1.3
  firebase_analytics: ^11.3.3
#  flutter_callkit_incoming_yoer: ^2.0.4+1
  flutter_callkit_incoming_yoer: ^2.0.4+1
  url_launcher: ^6.3.1
  get_thumbnail_video: ^0.7.3
  flutter_cache_manager: ^3.4.1

  pdf: ^3.11.1
  printing: ^5.13.4
  device_info_plus: ^11.3.0
  package_info_plus: ^8.1.1

 #hdfcpayment
  hypersdkflutter: ^4.0.25
  flutter_dotenv: ^6.0.0

dependency_overrides:
  floating: any
  flutter_ringtone_player: any
  record_platform_interface: 1.2.0
  record_linux: ^0.7.2


dev_dependencies:
  flutter_test: 
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/HE NEW LOGO Dark-03.png"
  min_sdk_android: 21 # optional
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
    - assets/sounds/
    - assets/videos/
    - assets/lottie/
    - .env
  fonts:
    - family: Plus Jakarta Sans
      fonts: 
        - asset: assets/fonts/PlusJakartaSansRomanBold.ttf
          weight: 700
        - asset: assets/fonts/PlusJakartaSansRomanMedium.ttf
          weight: 500
        - asset: assets/fonts/PlusJakartaSansRomanRegular.ttf
          weight: 400
        - asset: assets/fonts/PlusJakartaSansRomanSemiBold.ttf
          weight: 600
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterBold.ttf
          weight: 700
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
        - asset: assets/fonts/InterSemiBold.ttf
          weight: 600
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
    - family: Syne
      fonts: 
        - asset: assets/fonts/SyneMedium.ttf
          weight: 500
